name: mln131-minigame

services:
  backend:
    image: ${DOCKERHUB_USER:-local}/minigame-be:${TAG:-latest}
    build:
      context: ./minigame_be
      dockerfile: Dockerfile
    container_name: minigame-backend
    ports:
      - "8080:8080"
    environment:
      APP_SECURITY_ALLOWED_ORIGINS: ${APP_SECURITY_ALLOWED_ORIGINS:-http://localhost:5173}
      APP_SECURITY_JWT_SECRET: ${APP_SECURITY_JWT_SECRET:-01234567890123456789012345678901}
      APP_SECURITY_JWT_EXPIRATION_MINUTES: ${APP_SECURITY_JWT_EXPIRATION_MINUTES:-180}
    restart: unless-stopped

  frontend:
    image: ${DOCKERHUB_USER:-local}/minigame-fe:${TAG:-latest}
    build:
      context: ./minigame_fe
      dockerfile: Dockerfile
    container_name: minigame-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

